import type { WorkspaceData } from "./types";

export const demoData: WorkspaceData = {
  currentProfile: {
    id: "ryan",
    full_name: "Ryan",
    avatar_url: null,
    onboarding_completed: true,
    task_details_open_by_default: false,
  },
  profiles: [
    {
      id: "ryan",
      full_name: "Ryan",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
    },
    {
      id: "alex",
      full_name: "Alex Ryan",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
    },
    {
      id: "jordan",
      full_name: "Jordan Ryan",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
    },
  ],
  statuses: [
    {
      id: "backlog",
      name: "Backlog",
      color: "#64748b",
      sort_order: 0,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "todo",
      name: "Todo",
      color: "#2563eb",
      sort_order: 1,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "progress",
      name: "In Progress",
      color: "#d97706",
      sort_order: 2,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "review",
      name: "In Review",
      color: "#7c3aed",
      sort_order: 3,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "done",
      name: "Done",
      color: "#059669",
      sort_order: 4,
      order_revision: 0,
      is_default: true,
      is_completed: true,
    },
  ],
  categories: [
    {
      id: "chapter",
      name: "Chapters",
      description: "Work supporting local Ryan chapters.",
      color: "#0f766e",
      created_by: "ryan",
    },
    {
      id: "sponsors",
      name: "Sponsorships",
      description: "Partnership outreach and sponsor commitments.",
      color: "#c2410c",
      created_by: "ryan",
    },
    {
      id: "web",
      name: "Web / Tools",
      description: null,
      color: "#4338ca",
      created_by: "ryan",
    },
    {
      id: "events",
      name: "Events",
      description: "Meetup logistics and event production.",
      color: "#be123c",
      created_by: "ryan",
    },
    {
      id: "design",
      name: "Art & Design",
      description: null,
      color: "#7c3aed",
      created_by: "ryan",
    },
    {
      id: "collaborations",
      name: "Collaborations",
      description: null,
      color: "#0891b2",
      created_by: "ryan",
    },
  ],
  projects: [
    {
      id: "ryancon-2027",
      name: "RyanCon 2027",
      description: "Planning and production for RyanCon 2027.",
      links: [{ label: "RyanCon website", url: "https://ryancon.com" }],
      created_by: "ryan",
      archived_at: null,
      created_at: "2026-08-01T09:00:00Z",
    },
    {
      id: "september-meetup",
      name: "September Meetup",
      description: "Everything needed for the September gathering.",
      links: [],
      created_by: "ryan",
      archived_at: null,
      created_at: "2026-08-01T09:00:00Z",
    },
  ],
  subtasks: [],
  comments: [],
  activity: [],
  attachments: [],
  labels: [
    { id: "blocked", name: "Blocked", color: "#dc2626", created_by: "ryan" },
    { id: "website", name: "Website", color: "#4f46e5", created_by: "ryan" },
  ],
  taskAssignees: [],
  taskLabels: [],
  projectOwners: [
    { project_id: "ryancon-2027", profile_id: "ryan" },
    { project_id: "september-meetup", profile_id: "ryan" },
    { project_id: "september-meetup", profile_id: "alex" },
  ],
  taskCategories: [
    { task_id: "1", category_id: "events" },
    { task_id: "1", category_id: "collaborations" },
    { task_id: "2", category_id: "sponsors" },
    { task_id: "2", category_id: "design" },
    { task_id: "3", category_id: "chapter" },
    { task_id: "4", category_id: "web" },
    { task_id: "5", category_id: "chapter" },
  ],
  tasks: [
    {
      id: "1",
      title: "Confirm September venue",
      description: "Get the final room capacity and load-in details.",
      status_id: "progress",
      project_id: "september-meetup",
      assignee_id: "alex",
      created_by: "ryan",
      reported_by: "ryan",
      start_date: "2026-08-01",
      due_date: "2026-08-08",
      due_time: null,
      reminder_at: null,
      priority: "urgent",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T12:00:00Z",
      updated_at: "2026-08-01T12:00:00Z",
    },
    {
      id: "2",
      title: "Refresh sponsor prospectus",
      description: "Update benefits and current event dates.",
      status_id: "review",
      project_id: "ryancon-2027",
      assignee_id: "jordan",
      created_by: "ryan",
      reported_by: "ryan",
      start_date: null,
      due_date: "2026-08-12",
      due_time: null,
      reminder_at: null,
      priority: "high",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T11:00:00Z",
      updated_at: "2026-08-01T11:00:00Z",
    },
    {
      id: "3",
      title: "Publish chapter host checklist",
      description: null,
      status_id: "todo",
      project_id: null,
      assignee_id: null,
      created_by: "ryan",
      reported_by: "ryan",
      start_date: null,
      due_date: "2026-08-15",
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T10:00:00Z",
      updated_at: "2026-08-01T10:00:00Z",
    },
    {
      id: "4",
      title: "Fix RSVP confirmation copy",
      description: "Keep it warm, short, and unmistakably Ryan.",
      status_id: "backlog",
      project_id: null,
      assignee_id: "ryan",
      created_by: "ryan",
      reported_by: "ryan",
      start_date: null,
      due_date: null,
      due_time: null,
      reminder_at: null,
      priority: "low",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T09:00:00Z",
      updated_at: "2026-08-01T09:00:00Z",
    },
    {
      id: "5",
      title: "Send July volunteer thank-yous",
      description: null,
      status_id: "done",
      project_id: null,
      assignee_id: "alex",
      created_by: "ryan",
      reported_by: "ryan",
      start_date: null,
      due_date: "2026-08-02",
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 1024,
      completed_at: "2026-08-01T08:00:00Z",
      archived_at: "2026-08-15T08:00:00Z",
      created_at: "2026-08-01T08:00:00Z",
      updated_at: "2026-08-01T08:00:00Z",
    },
  ],
};
