import type { WorkspaceData } from "./workspace-types";

export const demoData: WorkspaceData = {
  canManageCategories: true,
  currentProfile: {
    id: "taylor",
    full_name: "Taylor Brooks",
    avatar_url: null,
    onboarding_completed: true,
    task_details_open_by_default: false,
    favorite_project_ids: ["website-refresh"],
  },
  profiles: [
    {
      id: "taylor",
      full_name: "Taylor Brooks",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
      favorite_project_ids: ["website-refresh"],
    },
    {
      id: "alex",
      full_name: "Alex Morgan",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
      favorite_project_ids: [],
    },
    {
      id: "jordan",
      full_name: "Jordan Lee",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
      favorite_project_ids: [],
    },
  ],
  statuses: [
    {
      id: "backlog",
      name: "Backlog",
      description: "Ideas and requests that are not ready to schedule yet.",
      color: "#64748b",
      sort_order: 0,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "todo",
      name: "Todo",
      description: "Ready to be picked up and worked on.",
      color: "#2563eb",
      sort_order: 1,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "progress",
      name: "In Progress",
      description: "Actively being worked on right now.",
      color: "#d97706",
      sort_order: 2,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "review",
      name: "In Review",
      description: "Waiting for feedback, approval, or final checks.",
      color: "#7c3aed",
      sort_order: 3,
      order_revision: 0,
      is_default: true,
      is_completed: false,
    },
    {
      id: "done",
      name: "Done",
      description: "Finished work that no longer needs action.",
      color: "#059669",
      sort_order: 4,
      order_revision: 0,
      is_default: true,
      is_completed: true,
    },
  ],
  categories: [
    {
      id: "operations",
      name: "Operations",
      description: "Day-to-day planning and internal team operations.",
      color: "#0f766e",
      links: [],
      tags: ["Chicago", "New York", "Los Angeles"],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "partnerships",
      name: "Partnerships",
      description: "Partner outreach, proposals, and shared commitments.",
      color: "#c2410c",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "web",
      name: "Product / Tools",
      description: null,
      color: "#4338ca",
      links: [],
      tags: ["Feature", "Improvement", "Bug"],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "events",
      name: "Events",
      description: "Event logistics, schedules, and production.",
      color: "#be123c",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "creative",
      name: "Creative",
      description: null,
      color: "#7c3aed",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "marketing",
      name: "Marketing",
      description: null,
      color: "#0891b2",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
  ],
  projects: [
    {
      id: "website-refresh",
      name: "Website Refresh",
      description: "Content, design, and launch work for the new website.",
      links: [{ label: "Project brief", url: "https://example.com/brief" }],
      created_by: "taylor",
      archived_at: null,
      created_at: "2026-08-01T09:00:00Z",
    },
    {
      id: "fall-launch",
      name: "Fall Launch",
      description: "Everything needed to prepare the fall product launch.",
      links: [],
      created_by: "taylor",
      archived_at: null,
      created_at: "2026-08-01T09:00:00Z",
    },
  ],
  subtasks: [],
  comments: [],
  activity: [],
  attachments: [],
  labels: [
    { id: "blocked", name: "Blocked", color: "#dc2626", created_by: "taylor" },
    { id: "website", name: "Website", color: "#4f46e5", created_by: "taylor" },
  ],
  taskAssignees: [],
  taskLabels: [],
  projectOwners: [
    { project_id: "website-refresh", profile_id: "taylor" },
    { project_id: "fall-launch", profile_id: "taylor" },
    { project_id: "fall-launch", profile_id: "alex" },
  ],
  categoryOwners: [
    { category_id: "events", profile_id: "taylor" },
    { category_id: "events", profile_id: "alex" },
    { category_id: "partnerships", profile_id: "taylor" },
    { category_id: "creative", profile_id: "alex" },
  ],
  taskCategories: [
    { task_id: "1", category_id: "events" },
    { task_id: "1", category_id: "marketing" },
    { task_id: "2", category_id: "partnerships" },
    { task_id: "2", category_id: "creative" },
    { task_id: "3", category_id: "operations" },
    { task_id: "4", category_id: "web" },
    { task_id: "5", category_id: "operations" },
  ],
  tasks: [
    {
      id: "1",
      task_number: 5,
      title: "Confirm launch venue",
      description: "Get the final room capacity and setup details.",
      status_id: "progress",
      project_id: "fall-launch",
      assignee_id: "alex",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: "2026-08-01",
      due_date: "2026-08-08",
      due_time: null,
      reminder_at: null,
      priority: "urgent",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T12:00:00Z",
      updated_at: "2026-08-01T12:00:00Z",
    },
    {
      id: "2",
      task_number: 4,
      title: "Refresh partner brief",
      description: "Update the proposal, benefits, and launch timeline.",
      status_id: "review",
      project_id: "website-refresh",
      assignee_id: "jordan",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: "2026-08-12",
      due_time: null,
      reminder_at: null,
      priority: "high",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T11:00:00Z",
      updated_at: "2026-08-01T11:00:00Z",
    },
    {
      id: "3",
      task_number: 3,
      title: "Publish onboarding checklist",
      description: null,
      status_id: "todo",
      project_id: null,
      assignee_id: null,
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: "2026-08-15",
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T10:00:00Z",
      updated_at: "2026-08-01T10:00:00Z",
    },
    {
      id: "4",
      task_number: 2,
      title: "Fix confirmation email copy",
      description: "Keep it warm, short, and easy to understand.",
      status_id: "backlog",
      project_id: null,
      assignee_id: "taylor",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: null,
      due_time: null,
      reminder_at: null,
      priority: "low",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: "2026-08-01T09:00:00Z",
      updated_at: "2026-08-01T09:00:00Z",
    },
    {
      id: "5",
      task_number: 1,
      title: "Send customer interview thank-yous",
      description: null,
      status_id: "done",
      project_id: null,
      assignee_id: "alex",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: "2026-08-02",
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 1024,
      completed_at: "2026-08-01T08:00:00Z",
      archived_at: "2026-08-15T08:00:00Z",
      created_at: "2026-08-01T08:00:00Z",
      updated_at: "2026-08-01T08:00:00Z",
    },
  ],
};
